### ISSUE TITLE
installer: check for an update situation

### ISSUE THREAD

**Issue by agroszer** [munin-monitoring/munin-node-win32#15] opened 2012-12-19 07:54 UTC
_Original author: agros...@gmail.com (February 07, 2011 12:30:04)_

Overwrite service name with the right version.

_Original issue: http://code.google.com/p/munin-node-win32/issues/detail?id=10_

**Comment by lemontree23** [comment] 2020-02-19 09:15
Outdated issue (opened 8 years ago)
Duplicate of #13

**Closed by lemontree23** 2020-02-19 09:15 UTC
Labels: duplicate, imported
